### PR TITLE
Add browserslist to package.json

### PR DESCRIPTION
**Pull request by taniaprocha**

### CODE REVIEW

**Comment by jfranciscosousa** [comment]
You are missing the plugin `polyfill` on `gatsby-config.js` - `plugins: [`gatsby-plugin-polyfill-io`]`.

**Comment by taniaprocha** [comment]
@jfranciscosousa it's already added.

**Comment by jfranciscosousa** [comment]
My bad 🤦‍♂️ didn't notice. We need to test on IE11 now

**Comment by jfranciscosousa** [comment]
Still doesn't solve the issue. But I believe this could be merged still, just not yet. Let me check if my other PR does something to fix this.

**Comment by taniaprocha** [comment]
Same error

**Comment by taniaprocha** [comment]
Maybe you can add this code to your PR

**Comment by jfranciscosousa** [comment]
Try https://github.com/genify/babel-plugin-transform-remove-strict-mode

**Comment by jfranciscosousa** [comment]
I'll try that on a new PR in the meantime

**Pull request merged**
